export const recipes = [
  {
    id: 1,
    title: "Spaghetti Carbonara",
    ingredients: ["Spaghetti", "Eggs", "Pancetta", "Parmesan", "Black Pepper"],
    instructions: "Cook pasta. Fry pancetta. Mix eggs and cheese. Combine all.",
    time: "25 min",
    servings: 2,
    image: "Spaghetti.jpg", 
    vegetarian: false,
  },
  {
    id: 2,
    title: "Chicken Curry",
    ingredients: ["Chicken", "Onions", "Garlic", "Curry Powder", "Coconut Milk"],
    instructions: "Sauté onions and garlic. Add chicken and curry powder. Pour coconut milk. Simmer.",
    time: "40 min",
    servings: 4,
    image: "Chicken.jpg",
    vegetarian: false,
  },
  {
    id: 3,
    title: "Veggie Stir-fry",
    image: "Stir.jpg", 
    ingredients: ["broccoli", "carrot", "bell pepper", "soy sauce", "tofu"],
    instructions: "Stir-fry veggies and tofu in soy sauce.",
    time: "20 mins",
    servings: 2,
    vegetarian: true,
  },
  {
    id: 4,
    title: "Salmon with Lemon",
    image: "Salmon.jpg", 
    ingredients: ["salmon", "lemon", "butter", "garlic", "parsley"],
    instructions: "Cook salmon with butter, garlic, and lemon juice.",
    time: "30 mins",
    servings: 2,
    vegetarian: false,
  },
  {
    id: 5,
    title: "Tacos",
    image: "Tacos.jpg", 
    ingredients: ["ground beef", "taco shells", "lettuce", "cheese", "sour cream"],
    instructions: "Cook beef, assemble tacos with toppings.",
    time: "20 mins",
    servings: 3,
    vegetarian: false,
  },
  {
    id: 6,
    title: "Vegetarian Pizza",
    image: "Pizza.jpg", 
    ingredients: ["pizza dough", "tomato sauce", "cheese", "vegetables"],
    instructions: "Top dough with sauce, veggies, and cheese, bake.",
    time: "25 mins",
    servings: 4,
    vegetarian: true,
  },
];

  